
#General Settings
[general_settings]
	#Enables additional debug logging.  THIS SETTING MAY CAUSE LAG!  Please only enable it if you are troubleshooting or reporting an issue.
	advanced_debugging = false
	#Prevents the shock effect from being applied to ANY entity, effectively removing it from the game.
	prevent_shock_effect = false

[item_settings]

	#Dragon Whistle Settings
	[item_settings.dragon_whistle]
		#Maximum range (in blocks) that dragons can hear the whistle from.  Higher values could cause lag when many entities are present.
		#Range: 1 ~ 512
		whistle_range = 64
		#Allows the whistle to select a specific dragon species to issue commands to.
		allow_species_select = true
		#Allows the whistle to select a specific dragon family to issue commands to (such as night furies, light furies, and night lights).
		allow_family_select = true
		#Allows the whistle to select a specific individual dragon to issue commands to.  Note that individual dragons must be named in order to select them.
		allow_individual_select = true
		#Cooldown time in ticks between whistle commands (per whistle).  Mostly used as a latency mitigation feature, to prevent command duplication.
		#Setting this option to 0 disables the cooldown.
		#Range: 0 ~ 60
		whistle_cooldown = 5

	#Dragon Cage Settings
	[item_settings.dragon_cage]
		#Allows creative mode players to bypass most restrictions for caging dragons, such as type, tame status, and owner restrictions.  Useful for server operators and for hecking around in singleplayer.
		creative_cage_override = true
		#Allows players to cage untamed dragons with the dragon cage.  This can pose balance issues or allow for griefing, so enable at your own risk!
		allow_cage_untamed = false
		#Allows players to cage dragons that have items in their inventory.  PLEASE NOTE, this will cause all items in the dragon's inventory (except for their saddle and the chest itself) to drop on the ground!  When disabled, dragons won't be able to be caged until all items are removed from their inventory.
		allow_cage_inventory = false
		#Allows players to release dragons from cages that don't belong to them.  This can pose balance issues or allow for griefing, so enable at your own risk!
		allow_release_not_yours = false
		#How many seconds it takes for a caged dragon's health to increase by half a heart.  Note that passive healing ONLY occurs while the cage is being carried by a player.
		#Setting this to 0 disables caged dragon healing.
		#Range: 0 ~ 300
		cage_heal_tick = 5
		#Cooldown time in ticks between cage pickups/releases (per cage).  Mostly used as a latency mitigation feature, to prevent pickup/release duplication.
		#Setting this option to 0 disables the cooldown.
		#Range: 0 ~ 60
		cage_cooldown = 5

[dragon_settings]
	#Prevents dragons from directly damaging their owners, or their owners' other tames.
	#Please note that this may not prevent ALL damage, such as that caused by walking into fire created by a dragon's fireball.
	prevent_dragon_friendly_fire = true

	[dragon_settings.gronckle_settings]
		#Allows gronckles to be carried in a dragon cage.  When this setting is enabled, other restrictions may still apply.  Disabling it will ALWAYS prevent gronckles from being picked up.
		allow_gronckle_capture = true

	[dragon_settings.light_fury_settings]
		#Allows light furies to be carried in a dragon cage.  When this setting is enabled, other restrictions may still apply.  Disabling it will ALWAYS prevent light furies from being picked up.
		allow_light_fury_capture = true

	[dragon_settings.deadly_nadder_settings]
		#Allows deadly nadders to be carried in a dragon cage.  When this setting is enabled, other restrictions may still apply.  Disabling it will ALWAYS prevent deadly nadders from being picked up.
		allow_nadder_capture = true

	[dragon_settings.monstrous_nightmare_settings]
		#Allows monstrous nightmares to be carried in a dragon cage.  When this setting is enabled, other restrictions may still apply.  Disabling it will ALWAYS prevent monstrous nightmares from being picked up.
		allow_monstrous_nightmare_capture = true

	[dragon_settings.night_fury_settings]
		#Allows night furies to be carried in a dragon cage.  When this setting is enabled, other restrictions may still apply.  Disabling it will ALWAYS prevent night furies from being picked up.
		allow_night_fury_capture = true

	[dragon_settings.night_light_settings]
		#Allows night lights to be carried in a dragon cage.  When this setting is enabled, other restrictions may still apply.  Disabling it will ALWAYS prevent night lights from being picked up.
		allow_night_light_capture = true

	[dragon_settings.skrill_settings]
		#Allows skrills to be carried in a dragon cage.  When this setting is enabled, other restrictions may still apply.  Disabling it will ALWAYS prevent skrills from being picked up.
		allow_skrill_capture = true
		#Prevents skrills from being damaged by lightning or acquiring the shock effect.
		#Please note that enabling this option effectively prevents skrills from fighting each other!
		skrill_lightning_immune = true

	[dragon_settings.speed_stinger_settings]
		#Allows speed stingers to be carried in a dragon cage.  When this setting is enabled, other restrictions may still apply.  Disabling it will ALWAYS prevent speed stingers from being picked up.
		allow_speed_stinger_capture = true

	[dragon_settings.stinger_settings]
		#Allows stingers to be carried in a dragon cage.  When this setting is enabled, other restrictions may still apply.  Disabling it will ALWAYS prevent stingers from being picked up.
		allow_stinger_capture = true

	[dragon_settings.terrible_terror_settings]
		#Allows terrible terrors to be carried in a dragon cage.  When this setting is enabled, other restrictions may still apply.  Disabling it will ALWAYS prevent terrible terrors from being picked up.
		allow_terror_capture = true

	[dragon_settings.triple_stryke_settings]
		#Allows triple strykes to be carried in a dragon cage.  When this setting is enabled, other restrictions may still apply.  Disabling it will ALWAYS prevent triple strykes from being picked up.
		allow_triple_stryke_capture = true

	[dragon_settings.hideous_zippleback_settings]
		#Allows zipplebacks to be carried in a dragon cage.  When this setting is enabled, other restrictions may still apply.  Disabling it will ALWAYS prevent zipplebacks from being picked up.
		allow_zippleback_capture = true

#Spawn Settings
[spawns]
	#IMPORTANT: This alternative spawn system is designed to compensate for an issue in Isle of Berk that prevents dragons from spawning in modded biomes.  It does NOT prevent Isle of Berk from also spawning dragons as per its own settings.
	#It is HIGHLY recommended that you use only one spawn system at a time, as using both may overspawn dragons.  If you are only running vanilla biomes (or Isle of Berk compatible biome mods like Terralith), either spawn system is viable.
	#However, if you are using biome mods such as Oh the Biomes You'll Go or Biomes O'Plenty, it is recommended that you use IoB Addons' system and remove dragon spawn values from the Isle of Berk config, as IoB Addons allows dragons to spawn in modded biomes.
	#Using both systems simultaneously won't actually break anything, but it may make it harder to adjust dragon rates to your liking due to having two sets of competing spawn values.
	use_ioba_spawns = false

